/**
 * 面杀辅助工具菜单 — 单一事实源
 *
 * 每个条目代表一个工具/武将卡片入口，定义其展示元数据。
 * 菜单顺序即为默认排序。
 */
const menus = [
  {
    name: '彼岸幽霜',
    route: '/tool/bi-an-you-shuang',
    image: {
      src: 'src/assets/images/menus/彼岸幽霜-刘辩-动态.gif',
      focalX: 50,
      focalY: 50,
      fit: 'cover',
    },
    themeColor: '#8B2252',
    packageName: '武将',
    orientation: 'vertical',
  },
  {
    name: '冰肌玉雪',
    route: '/tool/bing-ji-yu-xue',
    image: {
      src: 'src/assets/images/menus/冰肌玉雪-董白-动态.gif',
      focalX: 50,
      focalY: 50,
      fit: 'cover',
    },
    themeColor: '#A0522D',
    packageName: '武将',
    orientation: 'vertical',
  },
  {
    name: '赤壁链火',
    route: '/tool/chi-bi-lian-huo',
    image: {
      src: 'src/assets/images/menus/赤壁链火-卧龙凤雏-动态.gif',
      focalX: 50,
      focalY: 50,
      fit: 'cover',
    },
    themeColor: '#C41E3A',
    packageName: '武将',
    orientation: 'horizontal',
  },
  {
    name: '翻浪搏蛟',
    route: '/tool/fan-lang-bo-jiao',
    image: {
      src: 'src/assets/images/menus/翻浪搏蛟-周处-动态.gif',
      focalX: 50,
      focalY: 50,
      fit: 'cover',
    },
    themeColor: '#D2691E',
    packageName: '武将',
    orientation: 'horizontal',
  },
  {
    name: '烽火燎袁',
    route: '/tool/feng-huo-liao-yuan',
    image: {
      src: 'src/assets/images/menus/烽火燎袁-许攸-动态.gif',
      focalX: 50,
      focalY: 50,
      fit: 'cover',
    },
    themeColor: '#D4380D',
    packageName: '武将',
    orientation: 'vertical',
  },
  {
    name: '锋丽鬘影',
    route: '/tool/feng-li-man-ying',
    image: {
      src: 'src/assets/images/menus/锋丽鬘影-花鬘-动态.gif',
      focalX: 50,
      focalY: 50,
      fit: 'cover',
    },
    themeColor: '#9B1B30',
    packageName: '武将',
    orientation: 'vertical',
  },
  {
    name: '刚戾诡谋',
    route: '/tool/gang-li-gui-mou',
    image: {
      src: 'src/assets/images/menus/刚戾诡谋-程昱-动态.gif',
      focalX: 50,
      focalY: 50,
      fit: 'cover',
    },
    themeColor: '#8B4513',
    packageName: '武将',
    orientation: 'vertical',
  },
  {
    name: '共御风霜',
    route: '/tool/gong-yu-feng-shuang',
    image: {
      src: 'src/assets/images/menus/共御风霜-周妃-动态.gif',
      focalX: 50,
      focalY: 50,
      fit: 'cover',
    },
    themeColor: '#C9A94E',
    packageName: '武将',
    orientation: 'vertical',
  },
  {
    name: '娇媚芙蓉',
    route: '/tool/jiao-mei-fu-rong',
    image: {
      src: 'src/assets/images/menus/娇媚芙蓉-曹宪曹华-动态.gif',
      focalX: 50,
      focalY: 50,
      fit: 'cover',
    },
    themeColor: '#CD853F',
    packageName: '武将',
    orientation: 'vertical',
  },
  {
    name: '桀骜睥睨',
    route: '/tool/jie-ao-bi-ni',
    image: {
      src: 'src/assets/images/menus/桀骜睥睨-司马师-动态.gif',
      focalX: 50,
      focalY: 50,
      fit: 'cover',
    },
    themeColor: '#B22222',
    packageName: '武将',
    orientation: 'vertical',
  },
  {
    name: '金桂月华·卢氏',
    route: '/tool/jin-gui-yue-hua-lu',
    image: {
      src: 'src/assets/images/menus/金桂月华-卢氏-动态.gif',
      focalX: 50,
      focalY: 50,
      fit: 'cover',
    },
    themeColor: '#DAA520',
    packageName: '武将',
    orientation: 'vertical',
  },
  {
    name: '金桂月华·张琪瑛',
    route: '/tool/jin-gui-yue-hua-zhang',
    image: {
      src: 'src/assets/images/menus/金桂月华-张琪瑛-动态.gif',
      focalX: 50,
      focalY: 50,
      fit: 'cover',
    },
    themeColor: '#B8860B',
    packageName: '武将',
    orientation: 'vertical',
  },
  {
    name: '金枝玉叶·曹婴',
    route: '/tool/jin-zhi-yu-ye-cao',
    image: {
      src: 'src/assets/images/menus/金枝玉叶-曹婴-动态.gif',
      focalX: 50,
      focalY: 50,
      fit: 'cover',
    },
    themeColor: '#DAA520',
    packageName: '武将',
    orientation: 'vertical',
  },
  {
    name: '金枝玉叶·张星彩',
    route: '/tool/jin-zhi-yu-ye-zhang',
    image: {
      src: 'src/assets/images/menus/金枝玉叶-张星彩-动态.gif',
      focalX: 50,
      focalY: 50,
      fit: 'cover',
    },
    themeColor: '#C9A94E',
    packageName: '武将',
    orientation: 'vertical',
  },
  {
    name: '俪觞妙舞',
    route: '/tool/li-shang-miao-wu',
    image: {
      src: 'src/assets/images/menus/俪觞妙舞-王荣-动态.gif',
      focalX: 50,
      focalY: 50,
      fit: 'cover',
    },
    themeColor: '#8B2252',
    packageName: '武将',
    orientation: 'vertical',
  },
  {
    name: '林隐拾逸',
    route: '/tool/lin-yin-shi-yi',
    image: {
      src: 'src/assets/images/menus/林隐拾逸-卧龙诸葛-动态.gif',
      focalX: 50,
      focalY: 50,
      fit: 'cover',
    },
    themeColor: '#8B4513',
    packageName: '武将',
    orientation: 'horizontal',
  },
  {
    name: '落笔生花',
    route: '/tool/luo-bi-sheng-hua',
    image: {
      src: 'src/assets/images/menus/落笔生花 骆统.jpg',
      focalX: 50,
      focalY: 50,
      fit: 'cover',
    },
    themeColor: '#A0522D',
    packageName: '武将',
    orientation: 'horizontal',
  },
  {
    name: '破晓逐辰',
    route: '/tool/po-xiao-zhu-chen',
    image: {
      src: 'src/assets/images/menus/破晓逐辰-界郭嘉-静态.png',
      focalX: 50,
      focalY: 50,
      fit: 'cover',
    },
    themeColor: '#D2691E',
    packageName: '武将',
    orientation: 'vertical',
  },
  {
    name: '蒲月念兔',
    route: '/tool/pu-yue-nian-tu',
    image: {
      src: 'src/assets/images/menus/蒲月念兔-钟会-动态.gif',
      focalX: 50,
      focalY: 50,
      fit: 'cover',
    },
    themeColor: '#CD853F',
    packageName: '武将',
    orientation: 'vertical',
  },
  {
    name: '神龙佑主',
    route: '/tool/shen-long-you-zhu',
    image: {
      src: 'src/assets/images/menus/神龙佑主-神赵云-动态.gif',
      focalX: 50,
      focalY: 50,
      fit: 'cover',
    },
    themeColor: '#DAA520',
    packageName: '武将',
    orientation: 'horizontal',
  },
  {
    name: '雅柔映采',
    route: '/tool/ya-rou-ying-cai',
    image: {
      src: 'src/assets/images/menus/雅柔映采-族荀采-动态.gif',
      focalX: 50,
      focalY: 50,
      fit: 'cover',
    },
    themeColor: '#9B1B30',
    packageName: '武将',
    orientation: 'vertical',
  },
  {
    name: '银黛妆梅',
    route: '/tool/yin-dai-zhuang-mei',
    image: {
      src: 'src/assets/images/menus/银黛妆梅-杜夫人-动态.gif',
      focalX: 50,
      focalY: 50,
      fit: 'cover',
    },
    themeColor: '#B8860B',
    packageName: '武将',
    orientation: 'vertical',
  },
  {
    name: '绽火烽威',
    route: '/tool/zhan-huo-feng-wei',
    image: {
      src: 'src/assets/images/menus/绽火烽威-神陆逊-动态.gif',
      focalX: 50,
      focalY: 50,
      fit: 'cover',
    },
    themeColor: '#C41E3A',
    packageName: '武将',
    orientation: 'vertical',
  },
];

export default menus;
